name: threads-deploy

services:
  db:
    image: postgres:15
    container_name: threads-deploy-db
    volumes:
      - postgres_data_deploy:/var/lib/postgresql/data
    env_file:
      - conf/deploy/.env
    networks:
      - threads-backend-deploy
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: threads-deploy-redis
    volumes:
      - redis_data_deploy:/data
    networks:
      - threads-backend-deploy
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 3

  init-static:
    image: ${ECR_REPO_URL}:web-${IMAGE_TAG}
    container_name: threads-deploy-init-static
    command: python manage.py collectstatic --noinput
    env_file:
      - conf/deploy/.env
    volumes: 
      - static_volume:/app/staticfiles
    networks:
      - threads-backend-deploy

  web:
    image: ${ECR_REPO_URL}:web-${IMAGE_TAG}
    container_name: threads-deploy-web
    env_file:
      - conf/deploy/.env
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      init-static:
        condition: service_completed_successfully
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - threads-backend-deploy
      - threads-frontend-deploy
    healthcheck:
      test: ["CMD","curl","-f","http://localhost:8000/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  celery:
    image: ${ECR_REPO_URL}:celery-${IMAGE_TAG}
    container_name: threads-deploy-celery
    env_file:
      - conf/deploy/.env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - threads-backend-deploy
    healthcheck:
      test: ["CMD", "celery", "-A", "core", "inspect", "ping"]
      interval: 15s
      timeout: 5s
      start_period: 10s
      retries: 3

  celery-beat:
    image: ${ECR_REPO_URL}:celery-beat-${IMAGE_TAG}
    container_name: threads-deploy-celery-beat
    env_file:
      - conf/deploy/.env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    networks:
      - threads-backend-deploy
  
  nginx:
    image: ${ECR_REPO_URL}:nginx-${IMAGE_TAG}
    container_name: threads-deploy-nginx
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles:ro
    depends_on:
      web:
        condition: service_healthy
    networks:
      - threads-frontend-deploy
    healthcheck:
      test: ["CMD","curl","-fsS","http://localhost/healthz"]
      interval: 10s
      timeout: 3s
      retries: 3


volumes:
  static_volume:
  postgres_data_deploy:
  redis_data_deploy:

networks:
  threads-frontend-deploy:
    driver: bridge
  threads-backend-deploy:
    driver: bridge